---
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: 5dybuz.0bb7bso1vfxxiii6
    apiServerEndpoint: "10.0.1.9:6443"
    caCertHashes:
      - "sha256:ad3f5deb068b7f2dadf1841fbc86790a3fad68718fc5dad017b1b332c228ec5d"
nodeRegistration:
  name: ip-10-0-1-193.eu-central-1.compute.internal
  kubeletExtraArgs:
    cloud-provider: aws
